"""Add billing models

Revision ID: 03c3cfbe6364
Revises: 480edf56e02b
Create Date: 2026-09-17 17:51:29.958301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03c3cfbe6364'
down_revision: Union[str, None] = '480edf56e02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_events_organization_id'), ['organization_id'], unique=False)

    op.create_table('payment_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_subscription_id'), ['subscription_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        # batch_op.alter_column('context_type',
        #        existing_type=sa.VARCHAR(length=30),
        #        nullable=False,
        #        existing_server_default=sa.text("'PLATFORM_CONTEXT'::character varying"))
        batch_op.create_index('ix_audit_logs_action_created', ['action', 'created_at'], unique=False)
        # batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        # batch_op.create_index(batch_op.f('ix_audit_logs_context_type'), ['context_type'], unique=False)
        batch_op.create_index('ix_audit_logs_entity_type_id', ['entity_type', 'entity_id'], unique=False)
        # batch_op.create_index(batch_op.f('ix_audit_logs_event_hash'), ['event_hash'], unique=False)
        batch_op.create_index('ix_audit_logs_org_created', ['organization_id', 'created_at'], unique=False)
        # batch_op.create_index(batch_op.f('ix_audit_logs_sequence_number'), ['sequence_number'], unique=False)
        # batch_op.create_index(batch_op.f('ix_audit_logs_support_session_id'), ['support_session_id'], unique=False)
        # batch_op.create_index(batch_op.f('ix_audit_logs_target_user_id'), ['target_user_id'], unique=False)
        batch_op.create_index('ix_audit_logs_user_created', ['user_id', 'created_at'], unique=False)
        # batch_op.create_foreign_key(None, 'users', ['target_user_id'], ['id'], ondelete='SET NULL')
        # batch_op.create_foreign_key(None, 'support_sessions', ['support_session_id'], ['id'], ondelete='SET NULL')
        # batch_op.create_foreign_key(None, 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        pass
        # batch_op.create_index(batch_op.f('ix_companies_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        pass
        # batch_op.create_index(batch_op.f('ix_contacts_deleted_at'), ['deleted_at'], unique=False)


    with op.batch_alter_table('leads', schema=None) as batch_op:
        pass
        # batch_op.create_index(batch_op.f('ix_leads_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        pass
        # batch_op.create_index(batch_op.f('ix_organizations_deleted_at'), ['deleted_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        pass
        # batch_op.alter_column('token_version',
        #        existing_type=sa.INTEGER(),
        #        nullable=False,
        #        existing_server_default=sa.text('1'))
        # batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))
        batch_op.alter_column('token_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_deleted_at'))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_deleted_at'))


    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_deleted_at'))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_deleted_at'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_audit_logs_user_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_support_session_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_sequence_number'))
        batch_op.drop_index('ix_audit_logs_org_created')
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_hash'))
        batch_op.drop_index('ix_audit_logs_entity_type_id')
        batch_op.drop_index(batch_op.f('ix_audit_logs_context_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))
        batch_op.drop_index('ix_audit_logs_action_created')
        batch_op.alter_column('context_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'PLATFORM_CONTEXT'::character varying"))

    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_organization_id'))

    op.drop_table('payment_transactions')
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_events_organization_id'))

    op.drop_table('billing_events')
    # ### end Alembic commands ###
