"""Add contact_phones and call_records

Revision ID: 347a88ad7f4d
Revises: a2c3d4e5f6g7
Create Date: 2026-09-16 10:58:50.800675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '347a88ad7f4d'
down_revision: Union[str, None] = 'a2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_phones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('phone_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('is_sms_capable', sa.Boolean(), nullable=False),
    sa.Column('is_callable', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_phones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_phones_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_phones_phone_number'), ['phone_number'], unique=False)

    op.create_table('call_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('provider_call_id', sa.String(length=100), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('disposition', sa.String(length=50), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('ai_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_records_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_records_user_id'), ['user_id'], unique=False)

    pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    with op.batch_alter_table('call_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_call_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_call_records_lead_id'))

    op.drop_table('call_records')
    with op.batch_alter_table('contact_phones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_phones_phone_number'))
        batch_op.drop_index(batch_op.f('ix_contact_phones_contact_id'))

    op.drop_table('contact_phones')
    # ### end Alembic commands ###
