"""add_remaining_models

Revision ID: 480edf56e02b
Revises: 0c4f33c1c0ad
Create Date: 2026-09-16 17:34:33.816329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '480edf56e02b'
down_revision: Union[str, None] = '0c4f33c1c0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logout_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_sessions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('availability_status',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('availability_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_status_organization_id'), ['organization_id'], unique=False)

    op.create_table('break_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('break_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_break_sessions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_break_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('daily_call_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_call_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_call_plans_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_call_plans_user_id'), ['user_id'], unique=False)

    op.create_table('leave_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leave_requests_user_id'), ['user_id'], unique=False)

    op.create_table('communication_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('message_id', sa.String(length=100), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communication_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communication_logs_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communication_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('daily_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['daily_call_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_tasks_lead_id'), ['lead_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_tasks_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_tasks_plan_id'), ['plan_id'], unique=False)

    op.create_table('dedupe_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id_a', sa.String(length=36), nullable=False),
    sa.Column('lead_id_b', sa.String(length=36), nullable=False),
    sa.Column('match_confidence', sa.Numeric(), nullable=True),
    sa.Column('match_basis', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id_a'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id_b'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dedupe_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dedupe_candidates_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('global_companies', schema=None) as batch_op:
        pass

    with op.batch_alter_table('global_people', schema=None) as batch_op:
        pass

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('segment', sa.String(length=10), nullable=True))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_schema_name'), ['schema_name'], unique=False)

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segment', sa.String(length=10), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('segment')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_schema_name'))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('segment')
        batch_op.drop_column('lead_type')

    with op.batch_alter_table('global_people', schema=None) as batch_op:
        pass

    with op.batch_alter_table('global_companies', schema=None) as batch_op:
        pass

    with op.batch_alter_table('dedupe_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dedupe_candidates_organization_id'))

    op.drop_table('dedupe_candidates')
    with op.batch_alter_table('daily_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_tasks_plan_id'))
        batch_op.drop_index(batch_op.f('ix_daily_tasks_organization_id'))
        batch_op.drop_index(batch_op.f('ix_daily_tasks_lead_id'))

    op.drop_table('daily_tasks')
    with op.batch_alter_table('communication_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communication_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_communication_logs_lead_id'))

    op.drop_table('communication_logs')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_leave_requests_organization_id'))

    op.drop_table('leave_requests')
    with op.batch_alter_table('daily_call_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_call_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_call_plans_organization_id'))

    op.drop_table('daily_call_plans')
    with op.batch_alter_table('break_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_break_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_break_sessions_organization_id'))

    op.drop_table('break_sessions')
    with op.batch_alter_table('availability_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_status_organization_id'))

    op.drop_table('availability_status')
    with op.batch_alter_table('attendance_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_sessions_organization_id'))

    op.drop_table('attendance_sessions')
    # ### end Alembic commands ###
