"""add phase 3 models

Revision ID: 4ea614cc177f
Revises: b24631367345
Create Date: 2026-09-16 11:22:08.576370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ea614cc177f'
down_revision: Union[str, None] = 'b24631367345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence_delegations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('absent_user_id', sa.String(length=36), nullable=False),
    sa.Column('cover_user_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['absent_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cover_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('absence_delegations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_absence_delegations_id'), ['id'], unique=False)

    op.create_table('eod_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eod_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eod_reports_id'), ['id'], unique=False)

    op.create_table('telecaller_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('calls_made', sa.Integer(), nullable=True),
    sa.Column('total_talk_time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telecaller_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telecaller_sessions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('telecaller_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telecaller_sessions_id'))

    op.drop_table('telecaller_sessions')
    with op.batch_alter_table('eod_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eod_reports_id'))

    op.drop_table('eod_reports')
    with op.batch_alter_table('absence_delegations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absence_delegations_id'))

    op.drop_table('absence_delegations')
    # ### end Alembic commands ###
