"""batch_updates_phase10_13

Revision ID: 651077a665a1
Revises: a7a34b235040
Create Date: 2026-09-19 16:52:30.115691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '651077a665a1'
down_revision: Union[str, None] = 'a7a34b235040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_columns(table_name: str) -> set[str]:
    return {column["name"] for column in sa.inspect(op.get_bind()).get_columns(table_name)}


def _table_indexes(table_name: str) -> set[str]:
    return {index["name"] for index in sa.inspect(op.get_bind()).get_indexes(table_name)}


def upgrade() -> None:
    # These columns are retained only as legacy compatibility metadata.  The
    # authoritative pull state is the tenant projection (companies.source_
    # global_company_id), not a mutable flag on the global master row.  They
    # must nevertheless exist because the model and historical databases
    # contain them.  The old revision attempted to create indexes for columns
    # that no earlier clean migration created.
    for table_name in ('global_companies', 'global_people'):
        columns = _table_columns(table_name)
        with op.batch_alter_table(table_name, schema=None) as batch_op:
            if 'pull_status' not in columns:
                batch_op.add_column(sa.Column('pull_status', sa.String(length=30), nullable=True))
            if 'pulled_at' not in columns:
                batch_op.add_column(sa.Column('pulled_at', sa.DateTime(), nullable=True))
            if 'pulled_by_org_id' not in columns:
                batch_op.add_column(sa.Column('pulled_by_org_id', sa.String(length=36), nullable=True))
            if 'pulled_by_org_name' not in columns:
                batch_op.add_column(sa.Column('pulled_by_org_name', sa.String(length=255), nullable=True))
            index_name = f'ix_{table_name}_pulled_by_org_id'
            if index_name not in _table_indexes(table_name):
                batch_op.create_index(index_name, ['pulled_by_org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_people_pulled_by_org_id'))
        batch_op.drop_column('pulled_by_org_name')
        batch_op.drop_column('pulled_by_org_id')
        batch_op.drop_column('pulled_at')
        batch_op.drop_column('pull_status')

    with op.batch_alter_table('global_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_companies_pulled_by_org_id'))
        batch_op.drop_column('pulled_by_org_name')
        batch_op.drop_column('pulled_by_org_id')
        batch_op.drop_column('pulled_at')
        batch_op.drop_column('pull_status')

    # ### end Alembic commands ###
