"""batch_updates_phase10_13

Revision ID: 651077a665a1
Revises: a7a34b235040
Create Date: 2026-09-19 16:52:30.115691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '651077a665a1'
down_revision: Union[str, None] = 'a7a34b235040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_edit_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_edit_requests_entity_id'))

    op.drop_table('global_edit_requests')
    with op.batch_alter_table('global_companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_companies_pulled_by_org_id'), ['pulled_by_org_id'], unique=False)

    with op.batch_alter_table('global_people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_people_pulled_by_org_id'), ['pulled_by_org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_people_pulled_by_org_id'))

    with op.batch_alter_table('global_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_companies_pulled_by_org_id'))

    op.create_table('global_edit_requests',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('changes_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('global_edit_requests_requested_by_fkey')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('global_edit_requests_resolved_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('global_edit_requests_pkey'))
    )
    with op.batch_alter_table('global_edit_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_edit_requests_entity_id'), ['entity_id'], unique=False)

    # ### end Alembic commands ###
