"""Add product_service and import logic

Revision ID: a7a34b235040
Revises: 3280ba601d18
Create Date: 2026-09-19 16:21:08.243497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7a34b235040'
down_revision: Union[str, None] = '3280ba601d18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_services',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_services_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_services_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_product_service_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_import_jobs_default_product_service_id', 'product_services', ['default_product_service_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_service_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('product_service_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_product_service_id'), ['product_service_id'], unique=False)
        batch_op.create_foreign_key('fk_leads_product_service_id', 'product_services', ['product_service_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint('fk_leads_product_service_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_leads_product_service_id'))
        batch_op.drop_column('purpose')
        batch_op.drop_column('product_service_name')
        batch_op.drop_column('product_service_id')

    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_import_jobs_default_product_service_id', type_='foreignkey')
        batch_op.drop_column('default_product_service_id')

    with op.batch_alter_table('product_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_services_organization_id'))
        batch_op.drop_index(batch_op.f('ix_product_services_id'))

    op.drop_table('product_services')
    # ### end Alembic commands ###
