"""add followup and target models

Revision ID: b24631367345
Revises: 347a88ad7f4d
Create Date: 2026-09-16 11:17:21.072750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b24631367345'
down_revision: Union[str, None] = '347a88ad7f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followup_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('trigger_outcome', sa.String(length=50), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('followup_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_followup_policies_id'), ['id'], unique=False)

    op.create_table('telecaller_targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('target_calls', sa.Integer(), nullable=True),
    sa.Column('target_connects', sa.Integer(), nullable=True),
    sa.Column('target_talk_time_minutes', sa.Integer(), nullable=True),
    sa.Column('target_qualified_leads', sa.Integer(), nullable=True),
    sa.Column('target_conversions', sa.Integer(), nullable=True),
    sa.Column('target_revenue', sa.Float(), nullable=True),
    sa.Column('achieved_calls', sa.Integer(), nullable=True),
    sa.Column('achieved_connects', sa.Integer(), nullable=True),
    sa.Column('achieved_talk_time_minutes', sa.Integer(), nullable=True),
    sa.Column('achieved_qualified_leads', sa.Integer(), nullable=True),
    sa.Column('achieved_conversions', sa.Integer(), nullable=True),
    sa.Column('achieved_revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telecaller_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telecaller_targets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telecaller_targets_target_date'), ['target_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('telecaller_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telecaller_targets_target_date'))
        batch_op.drop_index(batch_op.f('ix_telecaller_targets_id'))

    op.drop_table('telecaller_targets')
    with op.batch_alter_table('followup_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_followup_policies_id'))

    op.drop_table('followup_policies')
    # ### end Alembic commands ###
