"""telecaller_targets

Revision ID: f3b71ca1f5f5
Revises: 6d87aa33e07f
Create Date: 2026-09-18 17:12:22.010017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3b71ca1f5f5'
down_revision: Union[str, None] = '6d87aa33e07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('global_data_pull_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_data_pull_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_global_data_pull_logs_pulled_at'))

    op.drop_table('global_data_pull_logs')
    with op.batch_alter_table('global_companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_companies_pulled_by_org_id'))
        batch_op.drop_constraint(batch_op.f('global_companies_pulled_by_org_id_fkey'), type_='foreignkey')
        batch_op.drop_column('pulled_by_org_id')
        batch_op.drop_column('pulled_at')
        batch_op.drop_column('pull_history')
        batch_op.drop_column('pull_status')
        batch_op.drop_column('pulled_by_org_name')

    with op.batch_alter_table('global_people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_people_pulled_by_org_id'))
        batch_op.drop_constraint(batch_op.f('global_people_pulled_by_org_id_fkey'), type_='foreignkey')
        batch_op.drop_column('pulled_by_org_id')
        batch_op.drop_column('pulled_at')
        batch_op.drop_column('pull_history')
        batch_op.drop_column('pull_status')
        batch_op.drop_column('pulled_by_org_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telecaller_targets', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telecaller_targets')

    with op.batch_alter_table('global_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pulled_by_org_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pull_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pull_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pulled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pulled_by_org_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('global_people_pulled_by_org_id_fkey'), 'organizations', ['pulled_by_org_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_global_people_pulled_by_org_id'), ['pulled_by_org_id'], unique=False)

    with op.batch_alter_table('global_companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pulled_by_org_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pull_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('pull_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pulled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pulled_by_org_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('global_companies_pulled_by_org_id_fkey'), 'organizations', ['pulled_by_org_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_global_companies_pulled_by_org_id'), ['pulled_by_org_id'], unique=False)

    op.create_table('global_data_pull_logs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('pulled_by', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('global_company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('global_contact_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('resulting_company_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('resulting_contact_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('resulting_lead_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('snapshot_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('pulled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['global_company_id'], ['global_companies.id'], name=op.f('global_data_pull_logs_global_company_id_fkey')),
    sa.ForeignKeyConstraint(['global_contact_id'], ['global_contacts.id'], name=op.f('global_data_pull_logs_global_contact_id_fkey')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('global_data_pull_logs_organization_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pulled_by'], ['users.id'], name=op.f('global_data_pull_logs_pulled_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('global_data_pull_logs_pkey'))
    )
    with op.batch_alter_table('global_data_pull_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_data_pull_logs_pulled_at'), ['pulled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_global_data_pull_logs_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###
